### ISSUE TITLE
test dm920

### ISSUE THREAD

**Issue by budinev** [Hains/openvision-dm920-python3#14]
Hi I'm testing your dm920 openpli image I detect on first boot after the bootlogo the screen turns pink and only after the enigma2 restart which takes place after setting the language the colors return to natural another thing in the automatic satellite search the dm920 crashes example I'm looking for hotbird and astra19.2 after the crash going back to the configuration only hotbird remains memorized it seems that by searching for astra it does not memorize and crashes the dm920 at the second configuration by inserting astra manually everything is ok
  other than these little things the image works well sorry my english is not good

**Comment by Hains** [comment]
Hi,

Pink screen in- langunage selection- confirmed.
Probably skin error.
Crash with autoDiseqc confirmed as well.

Didn't noticed these problems. as I always flash with backup and restore options.

Anyway, On TODO list.
Try to fix them one of these days.

Thanks for reporting.

**Comment by Hains** [comment]
Fix crash Autodisecq
https://github.com/OpenPLi/enigma2/commit/2a7d8186a37aebbd093ea6ce0f42dd42ce1926a1

**Comment by budinev** [comment]
thanks test ok
