### ISSUE TITLE
feed error

### ISSUE THREAD

**Issue by mr-unix01** [Hains/openvision-dm920-python3#18]
HI,
I created it in my PC
folders in apache2
but I have this error:
Downloading http://192.168.1.83/feeds/openpli-13.2/all/Packages.gz.
 * opkg_download_backend: Failed to download http://192.168.1.83/feeds/openpli-13.2/all/Packages.gz, wget returned 8.
Downloading http://192.168.1.83/feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz.
 * opkg_download_backend: Failed to download http://192.168.1.83/feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz, wget returned 8.
Downloading http://192.168.1.83/feeds/openpli-13.2/dm920/Packages.gz.
 * opkg_download_backend: Failed to download http://192.168.1.83/feeds/openpli-13.2/dm920/Packages.gz, wget returned 8.
 
my apache points
at this address it is
correct?
http://192.168.1.83/feeds/openpli-python3/

thanks

**Comment by Hains** [comment]
HI,

I see you have feeds/openpli-python3 and feeds/openpli-13.2 mixed.
Fault in Readme file.

You have 2 options:
1): Rename openpli-python3 to openpli-13.2, in 192.168.1.83/feeds directory.

or:

2:) Chane openpli-13.2 to openpli-python3 in the 3 opkg files.:  
-all-feed.conf.
-cortexa15hf-neon-vfpv4-feed.conf
-dm920-feed.conf

in /etc/opkg directoriy box.

Option 1 is the most easy way, as it is version independent.

I'll think about fix.

**Comment by Hains** [comment]
The dm920-feed.conf file for example should be like this:

src/gz dm920 http://192.168.1.83/feeds/openpli-python3/dm920

**Comment by Hains** [comment]
Fix:
https://github.com/Hains/openpli-dm920-python3/commit/089567bc7008b0552bc027bc0f07fa88fc76d3d4

Now the 3 feed config files points directly to openpli-python3, instead of openpli-13.2

Thanks for reporting.

**Comment by mr-unix01** [comment]
HI,
I renamed the folder but still the same problem.
Is my Apache correct?
![Schermata del 2024-04-24 12-26-39](https://github.com/Hains/openpli-dm920-python3/assets/167810150/79a5f285-98a7-4419-b069-2087d1f87bd4)
In the directoy 
http://192.168.1.83/feeds/openpli-13.2/
there are no symlinks
is empty

**Comment by Hains** [comment]
That can mean two things.
-The symlinks points to a non-existing location.
-Yoiu have the file permission problem.

Dit you try:

```
sudo chown -Rf <username> openpli-dm920-python3/build/tmp/deploy/ipk
```
?

**Comment by Hains** [comment]
Can you navigate with command line or with Nemo/Nautils to e.g.

/usr/var/www/html/feeds/openpli-13.2/all

Do you see the IPK files?

-If not, location is incorrect.
-If yes, file permission problem.

**Comment by Hains** [comment]
Sorry:
/var/www/html/feeds/openpli-13.2/all

So without the /usr.

**Comment by Hains** [comment]
Another fault, must be

sudo chown -Rf <username> openpli-dm920-python3/build/tmp/deploy/ipk

**Comment by mr-unix01** [comment]
in the directory
/var/www/html/feeds/openpli-13.2/
there are symlinks
![69197ad9-1568-4d34-a70b-8689f17e0c5c](https://github.com/Hains/openpli-dm920-python3/assets/167810150/0bce8c8b-a2df-480b-b1c9-79c50e8f1d6e)

that connect to ipk
I'll take a good look tomorrow

**Comment by mr-unix01** [comment]
![Schermata del 2024-04-24 22-20-27](https://github.com/Hains/openpli-dm920-python3/assets/167810150/1c2670f0-aea8-46ed-a690-f8e7916ab74c)
the click on the symlinks
show ikp
permissions have been given
sudo chown -Rf <username> openpli-dm920-python3/build/tmp/deploy/ipk

**Comment by Hains** [comment]
It's 
```
sudo chown -Rf  <your username> openpli-dm920-python3/build/tmp/deploy/ipk
```

I noticed that github throw away text between angle brackets if the text isn't in a code block.
That's why 'your username' is gone.
So is the correct command for ownership.

You can also try file permission: 

```
sudo chmod -Rf  755  openpli-dm920-python3/build/tmp/deploy/ipk
```

For me, changing ownership (chown) was sufficient to get the symlinks working in webbrowser Apache2.
I have version 2.4.58 BTW Ubuntu 23.10/24.04.

I saw Debian in your screenshot.
Perhaps 'following symlinks' isn't enabled by default in Debian?

Ubuntu, in:
/etc/apache2/sites-enabled/000-default.conf


<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>


You can also try to add or change code regarding FollowSymLinks in the

/etc/apache2/sites-enabled/apache2.conf file.

Restart Apache2 with:

```
sudo systemctl restart apache2
```
Or reboot PC.

**Comment by Hains** [comment]
```
sudo chmod -Rf  <your username> 755  openpli-dm920-python3/build/tmp/deploy/ipk
```

**Comment by Hains** [comment]
Previous post edited.

**Comment by mr-unix01** [comment]
my configuration in apache2.conf

<Directory /var/www/>
Options Indexes FollowSymLinks
AllowOverride all
Require all granted

but you need the file
..htaccess ?

**Comment by mr-unix01** [comment]
my directory on my PC where the ipk files are located is this:
![Schermata del 2024-04-25 10-29-41](https://github.com/Hains/openpli-dm920-python3/assets/167810150/eff27dda-59f0-43ea-8c2c-5c7a829474eb)

**Comment by mr-unix01** [comment]
log error from apache2
192.168.1.50 - - [25/Apr/2024:10:19:44 +0200] "GET /feeds/openpli-13.2/all/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:19:44 +0200] "GET /feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:19:44 +0200] "GET /feeds/openpli-13.2/dm920/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:19:49 +0200] "GET /feeds/openpli-13.2/all/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:19:49 +0200] "GET /feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:19:49 +0200] "GET /feeds/openpli-13.2/dm920/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:21:05 +0200] "GET /feeds/openpli-13.2/all/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:21:05 +0200] "GET /feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:21:05 +0200] "GET /feeds/openpli-13.2/dm920/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:22:48 +0200] "GET /feeds/openpli-13.2/all/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:22:48 +0200] "GET /feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:22:48 +0200] "GET /feeds/openpli-13.2/dm920/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:23:16 +0200] "GET /feeds/openpli-13.2/all/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:23:16 +0200] "GET /feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:23:16 +0200] "GET /feeds/openpli-13.2/dm920/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:28:14 +0200] "GET /feeds/openpli-13.2/all/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:28:14 +0200] "GET /feeds/openpli-13.2/cortexa15hf-neon-vfpv4/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"
192.168.1.50 - - [25/Apr/2024:10:28:14 +0200] "GET /feeds/openpli-13.2/dm920/Packages.gz HTTP/1.1" 403 494 "-" "Wget/1.24.5"

**Comment by Hains** [comment]
No need for .htacces.

Try:

```
sudo chown -Rf  TypeHereYourUserName  openpli-dm920-python3
```
Any error?

Location ipk files is correct.
Configuration Apache2 seems OK either..

First you must see the symlinks in your webbrowser, otherwise no go.

Copy a regular file to  e.g:

```
/var/www/html/feeds/openpli-13.2/all
```
Can you see the 'all' directory with that file now?

**Comment by Hains** [comment]
I mean:

A regular file in:

```
/var/www/html/feeds/openpli-13.2/
````

**Comment by mr-unix01** [comment]
denied!
![Schermata del 2024-04-25 11-52-55](https://github.com/Hains/openpli-dm920-python3/assets/167810150/2a9c847e-8b61-45ec-ab0d-c1892e113796)

**Comment by mr-unix01** [comment]
denied!
![Schermata del 2024-04-25 11-56-09](https://github.com/Hains/openpli-dm920-python3/assets/167810150/1f8fd51b-78b1-4030-90bf-dff203241e6f)

**Comment by Hains** [comment]
You must use sudo.

In terninal:

sudo cp 

Or start your file manager in terminal with sudo.

So:

sudo nautilus

or  

sudo nemo

Ot whatever file manger you are using,

**Comment by mr-unix01** [comment]
ok if I open nautilus with "su" or "sudo" it copies the files without problems to /var/www/html/feeds/openpli-13.2/

**Comment by Hains** [comment]
Now you can probably see that file in your webbrowswer, but not the symlinks.
Correct?

**Comment by mr-unix01** [comment]
the file downloads without problems from pc
![Schermata del 2024-04-25 12-22-00](https://github.com/Hains/openpli-dm920-python3/assets/167810150/70a1eadd-3327-43bf-b278-601c17f5d4fc)

**Comment by mr-unix01** [comment]
the symlinks are not there

**Comment by Hains** [comment]
Did you try:

```
sudo  chown -Rf  DigitaQuiIlTuoNomeUtente  openpli-dm920-python3
```
? And any errors ?

**Comment by mr-unix01** [comment]
No error
![Schermata del 2024-04-25 12-33-57](https://github.com/Hains/openpli-dm920-python3/assets/167810150/2168a202-697a-42cd-b930-bd8423c19836)

**Comment by Hains** [comment]
Hmm..
Then I'm out of options I'm afraid.

For me it did the trick and that was sufficient.

You can experiment with the Apache2 config files (<Directory /var/www/)>.

You can  try:

```
sudo chmod -Rf  777  openpli-dm920-python3/build/tmp/deploy/ipk
```

So instead of 755.You never know.

Oterwise nothing left to Google on 'symlinks not working  Apache2, with and without  your distro and version.

**Comment by mr-unix01** [comment]
error log  my apache

[Fri Apr 26 09:25:59.736050 2024] [core:error] [pid 840216:tid 140686997309120] [client 176.46.240.109:40667] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/feeds/openpli-13.2/all
[Fri Apr 26 09:25:59.775683 2024] [core:error] [pid 840216:tid 140687022487232] [client 176.46.240.109:40668] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/feeds/openpli-13.2/cortexa15hf-neon-vfpv4
[Fri Apr 26 09:25:59.814873 2024] [core:error] [pid 840216:tid 140687131526848] [client 176.46.240.109:40669] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/feeds/openpli-13.2/dm920
[Fri Apr 26 09:26:10.378255 2024] [core:error] [pid 840216:tid 140687156704960] [client 176.46.240.109:40670] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/feeds/openpli-13.2/all
[Fri Apr 26 09:26:10.418126 2024] [core:error] [pid 840216:tid 140687014094528] [client 176.46.240.109:40671] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/feeds/openpli-13.2/cortexa15hf-neon-vfpv4
[Fri Apr 26 09:26:10.448324 2024] [core:error] [pid 840216:tid 140686988916416] [client 176.46.240.109:40672] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/feeds/openpli-13.2/dm920

**Comment by Hains** [comment]
Symbolic link not allowed or link target not accessible

One thing to try:

```
sudo chmod -R 755 /var/www/html/feeds
```

**Comment by Hains** [comment]
https://repost.aws/questions/QUmcp9btx6SmKdccQBuNNokA/ah00037-symbolic-link-not-allowed-or-link-target-not-accessible-var-www-html-flaskproject

**Comment by mr-unix01** [comment]
but have you tried the configuration? apache2 has a **www-data** user that must have home permissions

**Comment by Hains** [comment]
I never had to do something with www-data myself.

www-data is mentioned In the /etc/apache2/envvars file:

```
# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
```

**Comment by mr-unix01** [comment]
the update works without errors now
I solved it like this
https://askubuntu.com/questions/749697/how-do-i-give-myself-access-to-var-www-to-create-and-edit-files-and-folders-in
the update works without errors now
I solved it like this
but opkg upgrade doesn't download anything
![Schermata del 2024-04-28 17-05-56](https://github.com/Hains/openpli-dm920-python3/assets/167810150/13aceb29-e9bc-4d2d-b677-0c7d2c99b6ae)

**Comment by mr-unix01** [comment]
![Schermata del 2024-04-29 16-32-46](https://github.com/Hains/openpli-dm920-python3/assets/167810150/2ca90b7c-833c-47b5-b181-5d5b74e87c2e)
![Schermata del 2024-04-29 16-37-42](https://github.com/Hains/openpli-dm920-python3/assets/167810150/2f1442f7-4467-48a1-b5b8-149feb5b6e7d)
Thanks a lot
now everything works I cleaned up my apache,
there is a bug in the image
it is not possible to change password

**Comment by Hains** [comment]
That's a known bug (glibc?).
No solution yet.

6 months ago, it was working fine.

Password is not  needed with settop boxes.
Everything is running under Root by default.
By default there is no password.

**Comment by Hains** [comment]
Solution on the way.
Probably in the afternoon(build from scratch running)  after test.

arc4random needs to be removed from glibc.

Didn't had a high priority to fix this, as I always flash image with backup/restore enabled in webbrowser.
That restored my password as well.

**Comment by Hains** [comment]
Fix:
https://github.com/Hains/openpli-dm920-python3/commit/cb00e2efa41225eedfe8e3355817c26a6352c71c

This triggers a  (an almost) complete re-build.
So I added an OE-core update too this time. 

With a complete re-build, it's better to delete the build directory inside openpli-dm920-python to prevent (possible) failures.
Also the sstate-cache dir is growing, especially after a complete re-build.
And you will running out of disk space after a while.

When you don't delete the build dir, it will save you some time, as it doesn't trigger a rebuild of the native packages (e.g. python3-native_3.12.3).
It's not mandatory, but recommend.

**Comment by mr-unix01** [comment]
Thanks a lot,  now it works
![Schermata del 2024-05-01 15-39-30](https://github.com/Hains/openpli-dm920-python3/assets/167810150/62c78f0e-5321-4194-9c90-e5b47ebd0ff0)

**Comment by mr-unix01** [comment]
![3957D134-0C59-4712-BA62-F22056461754](https://github.com/Hains/openpli-dm920-python3/assets/167810150/0b128cad-00a7-4a5c-a9a7-2437d91a71fd)
I have this  two problem
by loading this kernel-module-8821cu-3.14-1.17-dm920_5.8.1-r0_dm920.ipk
and openwebif
![Schermata del 2024-05-01 16-26-10](https://github.com/Hains/openpli-dm920-python3/assets/167810150/67dbebb9-3ab8-4324-9f05-491c2f5c90d6)

**Comment by mr-unix01** [comment]
Tomorrow I will recompile and delete the tmp folder

**Comment by Hains** [comment]
No need for that.

Problem seems to occur when you flash the image directly after a build from scratch.
So run 'make image' again before box flash.

You have already flashed image, now you can try with telnet:

```
init 4
opkg update && opkg upgrade
opkg install enigma-info --force-reinstall
init 3
```

Problem is empty kernel string  in /usr/lib/enigma-info file, line 34
When 'opkg install enigma-info --force-reinstall' doesn't work:

Change line 34 from:

```
kernel = ''
```
to:
```
kernel='3.14-1.17-dm920'
```
You can also check 
```
openpli-dm920-python3/build/tmp/deploy/enigma-info/dm920.txt
```
file.

And restart Enigma2 with:
```
init 4
init 3
```

I will take a look at  error wifi driver later.

**Comment by mr-unix01** [comment]
sorry for a new bug if you look at image information
![ccf75f4d-f528-47f8-9a3a-01efc0112d6f](https://github.com/Hains/openpli-dm920-python3/assets/167810150/3a1ab3d9-1541-466c-b037-7111e8b46a94)

**Comment by Hains** [comment]
Try:

```
git config --global --add safe.directory /home/flavio/openpli-dm920-python3
```

And reinstall enigma-info.

Problem is empty oe string. line 48

must be:
```
oe=HEAD (04)
```


I'm planning to hard code kernel version and OE-core to avoid these problems.

**Comment by Hains** [comment]
Reinstall enigma-info after 'make image'

**Comment by mr-unix01** [comment]
why these?
![Schermata del 2024-05-03 03-00-30](https://github.com/Hains/openpli-dm920-python3/assets/167810150/bb6aeb0e-11b5-41fc-b99d-29f893cc2a11)

**Comment by Hains** [comment]
Because python3-twisted is broken in meta-openembedded.
Fix:
https://github.com/Hains/openpli-dm920-python3/commit/e5acc0f3f8904b36b2e78902b04550da171ca1f4

Until it's fixed in meta-openembedded.

Update your OE-core.

Perhaps you need to delele build/tmp dir, not build! if you still have error.

**Comment by Hains** [comment]
Regarding the wifi driver.
8821cu is already installed by default in image.

The /lib/modules/3.14-1.17-dm920/kernel/drivers/net/wireless/8821cu.ko file is present.

No need to install.
I can't check myself, as I don't have a WiFi dongle.
The recipe is the same as in OpenPLi core.
OE-A has only KCFLAGS for DreamOne and DreamTwo boxes.
And it has bc-native as dependency (Arbitrary precision calculator language).

Only thing I noticed.
With my Uclan Usytm4kpro the kernel is just 4.4.35.
So you can try to rename 3.14-1.17-dm920 to 3.14, so to this path:

/lib/modules/3.14/kernel/drivers/net/wireless/8821cu.ko

**Comment by mr-unix01** [comment]
it works 
thank you
