### ISSUE TITLE
python3-future 

### ISSUE THREAD

**Issue by mr-unix01** [Hains/openvision-dm920-python3#19]
HI,
can something be done?
Thank you
![Schermata del 2024-06-10 17-25-37](https://github.com/Hains/openpli-dm920-python3/assets/167810150/0c3f9e60-fc32-4d00-a6ef-4e9fcf6374d2)

**Comment by Hains** [comment]
https://github.com/Hains/openpli-dm920-python3/commit/a09142a9bcb2c36cd591cbe054cfa1e0d62aee83

**Comment by mr-unix01** [comment]
no work,,,,🥹
![Schermata del 2024-06-11 16-14-03](https://github.com/Hains/openpli-dm920-python3/assets/167810150/3d49e2b9-d230-4fd4-b478-9644c15994fb)

**Comment by Hains** [comment]
You can ignore the warning.
I don't see any error or problem.

**Comment by mr-unix01** [comment]
ok but the plugin is not installed
![a4b8c865-e723-4a14-aab5-075f8e18e742](https://github.com/Hains/openpli-dm920-python3/assets/167810150/02db7eee-59b5-419c-a110-bb55ff41d148)

**Comment by Hains** [comment]
That is more clear.
Yes the imp module has been removed with Python 3.12.
So the plugin is not compatible with Python 3.12

Needs porting like Openwebif:
https://github.com/Hains/openpli-dm920-python3/commit/b9399d36192911f7ea057e3464fea353869d7b3d

Plugin is not from feed. 
Feed has no vpnmanager.
Can only be fixed if source code is present in ipk file.
